language: cpp
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0 # clang 5.0
      - ubuntu-toolchain-r-test # gcc-6
    packages:
      - clang-5.0
      - g++-6
before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew upgrade cmake; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CC=clang-5.0; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CXX=clang++-5.0; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CC=gcc-6; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CXX=g++-6; fi

  - cd dependencies
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch v8
  - cd v8
  - git checkout tags/6.0.286.55
  - gclient sync
  - gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64" is_component_build=false'
  - ninja -C out.gn/x64.release
  - cd ../..
script: cmake -DSTATIC_V8=0 -DWITH_V8=1 . && make VERBOSE=1
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
