language: cpp
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0 # clang 5.0
      - ubuntu-toolchain-r-test # gcc-6
    packages:
      - clang-5.0
      - g++-6
before_install:
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CC=clang-5.0; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CXX=clang++-5.0; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CC=gcc-6; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CXX=g++-6; fi

  - if [ $WITH_V8 == 1 ]; then cd dependencies; fi
  - if [ $WITH_V8 == 1 ]; then git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git; fi
  - if [ $WITH_V8 == 1 ]; then export PATH=`pwd`/depot_tools:"$PATH"; fi
  - if [ $WITH_V8 == 1 ]; then fetch v8; fi
  - if [ $WITH_V8 == 1 ]; then cd v8; fi
  - if [ $WITH_V8 == 1 ]; then git checkout tags/6.0.286.55; fi
  - if [ $WITH_V8 == 1 ]; then gclient sync; fi
  - if [ $WITH_V8 == 1 ] && [ $STATIC_V8 == 0 ]; then gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64" is_component_build=true symbol_level=0'; fi
  - if [ $WITH_V8 == 1 ] && [ $STATIC_V8 == 1 ]; then gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64" is_component_build=false v8_static_library=true symbol_level=0'; fi
  - if [ $WITH_V8 == 1 ]; then ninja -C out.gn/x64.release v8; fi
  - if [ $WITH_V8 == 1 ]; then cd ../..; fi
script: cmake -DSTATIC_V8=$STATIC_V8 -DWITH_V8=$WITH_V8 -DSYSTEM_V8=0 . && make -j2 VERBOSE=1
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  - WITH_V8=0
  - WITH_V8=1 STATIC_V8=0
  - WITH_V8=1 STATIC_V8=1

# OS X build on travis takes too long and will probably fail because of that
matrix:
  allow_failures:
    - os: osx
