language: cpp
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - llvm-toolchain-precise-3.7 # clang 3.7
      - ubuntu-toolchain-r-test # gcc-5
    packages:
      - clang-3.7
      - cmake
      - cmake-data
      - g++-5
before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew upgrade cmake; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CC=clang-3.7; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CXX=clang++-3.7; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CC=gcc-5; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CXX=g++-5; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export GYPFLAGS="-Dclang=0"; fi

  - cd dependencies
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch v8
  - cd v8
  - git checkout tags/5.1.84
  - gclient sync
  - make library=static x64.release
  - cd ../..
script: cmake -DV8_LIB=dependencies/v8/out/x64.release/ -DSTATIC_V8=1 . && make VERBOSE=1
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
