language: cpp
sudo: required
dist: trusty
before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew upgrade cmake; fi
script: cmake . && make
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
