version: "2.1"

services:
  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - ./agdg-client/dist:/var/www/html:ro,z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    ports:
     - "80:80"

  agdgserver:
    build: .
    volumes:
      - ./agdg-client/dist/content:/srv/agdg-server/agdg-client/dist/content:z
      - ./config:/srv/agdg-server/config:ro,z
      - ./db:/srv/agdg-server/db:z
      - ./world:/srv/agdg-server/world:ro,z
    ports:
     - "9002:9002"
     - "9003:9003"
